name: happy_money
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar: ^5.0.2
  flutter_screenutil: ^5.8.4
  diamond_bottom_bar: ^1.0.0
  bottom_bar_with_sheet: ^2.4.0
  fk_toggle: ^0.1.4
  toggle_switch: ^2.1.0
  syncfusion_flutter_calendar: ^22.1.39
  flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker_plus: ^2.0.1
  hive:
  hive_flutter:
  path_provider:
  hive_generator:
  currency_text_input_formatter: ^2.1.10
  intl:
  flutter_switch:
  carousel_slider: ^4.2.1
  fluttertoast:
  uuid: ^4.0.0
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable:

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre
  hive_generator:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
